name: MinecraftAccountVerification
version: ${project.version}
main: com.nexuswhitelist.verification.Verification
api-version: 1.13
authors: [Zapdos26]
description: Minecraft Account Verification for Nexus Whitelist
website: https://nexuswhitelist.com
commands:
  link:
    description: Gives a Minecraft Token associated with your Minecraft Account
    usage: /link
    permission: minecraftaccountverification.link
    permission-message: You do not have the minecraftaccountverification.link permission.
permissions:
  minecraftaccountverification.link:
    description: Allows for /link command
    default: true